sbatch slurm_0.sbatch 
sbatch slurm_1.sbatch 
sbatch slurm_2.sbatch 
sbatch slurm_3.sbatch 
sbatch slurm_4.sbatch 
sbatch slurm_5.sbatch 
sbatch slurm_6.sbatch 
sbatch slurm_7.sbatch 
sbatch slurm_8.sbatch 
sbatch slurm_9.sbatch 
#sbatch slurm_MC.sbatch 
#sbatch slurm_DY.sbatch
#sbatch slurm_data.sbatch 
#
#sbatch slurm_EGC_0.sbatch
#sbatch slurm_EGC_1.sbatch
#sbatch slurm_EGC_2.sbatch
#sbatch slurm_EGC_3.sbatch
#sbatch slurm_EGC_4.sbatch
#sbatch slurm_EGC_5.sbatch
#sbatch slurm_EGC_6.sbatch
#sbatch slurm_EGC_7.sbatch
#sbatch slurm_EGC_8.sbatch
#sbatch slurm_EGC_9.sbatch
#
#sbatch slurm_EGD_0.sbatch
#sbatch slurm_EGD_1.sbatch
#sbatch slurm_EGD_2.sbatch
#sbatch slurm_EGD_3.sbatch
#sbatch slurm_EGD_4.sbatch
#sbatch slurm_EGD_5.sbatch
#sbatch slurm_EGD_6.sbatch
#sbatch slurm_EGD_7.sbatch
#sbatch slurm_EGD_8.sbatch
#sbatch slurm_EGD_9.sbatch
#
#sbatch slurm_EGE_0.sbatch
#sbatch slurm_EGE_1.sbatch
#sbatch slurm_EGE_2.sbatch
#sbatch slurm_EGE_3.sbatch
#sbatch slurm_EGE_4.sbatch
#sbatch slurm_EGE_5.sbatch
#sbatch slurm_EGE_6.sbatch
#sbatch slurm_EGE_7.sbatch
#sbatch slurm_EGE_8.sbatch
#sbatch slurm_EGE_9.sbatch
#
#sbatch slurm_EGF_0.sbatch
#sbatch slurm_EGF_1.sbatch
#sbatch slurm_EGF_2.sbatch
#sbatch slurm_EGF_3.sbatch
#sbatch slurm_EGF_4.sbatch
#sbatch slurm_EGF_5.sbatch
#sbatch slurm_EGF_6.sbatch
#sbatch slurm_EGF_7.sbatch
#sbatch slurm_EGF_8.sbatch
#sbatch slurm_EGF_9.sbatch
#
#sbatch slurm_SEB_0.sbatch
#sbatch slurm_SEB_1.sbatch
#sbatch slurm_SEB_2.sbatch
#sbatch slurm_SEB_3.sbatch
#sbatch slurm_SEB_4.sbatch
#sbatch slurm_SEB_5.sbatch
#sbatch slurm_SEB_6.sbatch
#sbatch slurm_SEB_7.sbatch
#sbatch slurm_SEB_8.sbatch
#sbatch slurm_SEB_9.sbatch
#
#sbatch slurm_SEC_0.sbatch
#sbatch slurm_SEC_1.sbatch
#sbatch slurm_SEC_2.sbatch
#sbatch slurm_SEC_3.sbatch
#sbatch slurm_SEC_4.sbatch
#sbatch slurm_SEC_5.sbatch
#sbatch slurm_SEC_6.sbatch
#sbatch slurm_SEC_7.sbatch
#sbatch slurm_SEC_8.sbatch
#sbatch slurm_SEC_9.sbatch
#
#sbatch slurm_SED_0.sbatch
#sbatch slurm_SED_1.sbatch
#sbatch slurm_SED_2.sbatch
#sbatch slurm_SED_3.sbatch
#sbatch slurm_SED_4.sbatch
#sbatch slurm_SED_5.sbatch
#sbatch slurm_SED_6.sbatch
#sbatch slurm_SED_7.sbatch
#sbatch slurm_SED_8.sbatch
#sbatch slurm_SED_9.sbatch
#
#sbatch slurm_SEE_0.sbatch
#sbatch slurm_SEE_1.sbatch
#sbatch slurm_SEE_2.sbatch
#sbatch slurm_SEE_3.sbatch
#sbatch slurm_SEE_4.sbatch
#sbatch slurm_SEE_5.sbatch
#sbatch slurm_SEE_6.sbatch
#sbatch slurm_SEE_7.sbatch
#sbatch slurm_SEE_8.sbatch
#sbatch slurm_SEE_9.sbatch
#
#sbatch slurm_SEF_0.sbatch
#sbatch slurm_SEF_1.sbatch
#sbatch slurm_SEF_2.sbatch
#sbatch slurm_SEF_3.sbatch
#sbatch slurm_SEF_4.sbatch
#sbatch slurm_SEF_5.sbatch
#sbatch slurm_SEF_6.sbatch
#sbatch slurm_SEF_7.sbatch
#sbatch slurm_SEF_8.sbatch
#sbatch slurm_SEF_9.sbatch
