import numpy as np

output = {}
branches = {"Run": long,
			"Event": long,
			"LumiSect": long,
			"nMuons": int,
			"nGoodMuons": int,
			"nbJets": int,
			"pTL1": float,
			"pTL2": float,
			"pTL3": float,
			"idL1": int,
			"idL2": int,
			"idL3": int,
			"etaL1": float,
			"etaL2": float,
			"etaL3": float,
			"phiL1": float,
			"phiL2": float,
			"phiL3": float,
			"IsoL1": float,
			"IsoL2": float,
			"IsoL3": float,
			"ip3dL1": float,
			"ip3dL2": float,
			"ip3dL3": float,
			"sip3dL1": float,
			"sip3dL2": float,
			"sip3dL3": float,
			"massL1": float,
			"massL2": float,
			"massL3": float,
			"tightIdL1": int,
			"tightIdL2": int,
			"tightIdL3": int,
			"medIdL1": int,
			"medIdL2": int,
			"medIdL3": int,
			"sourceL1": int,
			"sourceL2": int,
			"sourceL3": int,
			"maxdxy": float,
			"maxdz": float,
			"dR12": float,
			"dR13": float,
			"dR23": float,
			"m3l": float,
			"m4l": float,
			"mt": float,
			"met": float,
			"met_phi": float,
			"genWeight": float,
			"pileupWeight": float,
			"passedDiMu1": int,
			"passedDiMu2": int,
			"passedTriMu": int,
			}


for branch in branches:
	output[branch] = np.array([])

