import numpy as np

output = {}
branches = {"Run": np.int64,
			"Event": np.int64,
			"LumiSect": np.int64,
			"nMuons": int,
			"nGoodMuons": int,
			"nElectrons": int,
			"nGoodElectrons": int,
			"nLeptons": int,
			"nGoodLeptons": int,
			"nbJets": int,
			"nJets": int,
			"pTL1": float,
			"pTL2": float,
			"pTL3": float,
			"pTL4": float,
			"idL1": int,
			"idL2": int,
			"idL3": int,
			"idL4": int,
			"etaL1": float,
			"etaL2": float,
			"etaL3": float,
			"etaL4": float,
			"phiL1": float,
			"phiL2": float,
			"phiL3": float,
			"phiL4": float,
			"IsoL1": float,
			"IsoL2": float,
			"IsoL3": float,
			"IsoL4": float,
			"ip3dL1": float,
			"ip3dL2": float,
			"ip3dL3": float,
			"ip3dL4": float,
			"sip3dL1": float,
			"sip3dL2": float,
			"sip3dL3": float,
			"sip3dL4": float,
			"massL1": float,
			"massL2": float,
			"massL3": float,
			"massL4": float,
			"tightIdL1": int,
			"tightIdL2": int,
			"tightIdL3": int,
			"tightIdL4": int,
			"medIdL1": int,
			"medIdL2": int,
			"medIdL3": int,
			"medIdL4": int,
			"looseIdL1": int,
			"looseIdL2": int,
			"looseIdL3": int,
			"looseIdL4": int,
			"mvaIdL1": int,
			"mvaIdL2": int,
			"mvaIdL3": int,
			"mvaIdL4": int,
			"softIdL1": int,
			"softIdL2": int,
			"softIdL3": int,
			"softIdL4": int,
			"sourceL1": int,
			"sourceL2": int,
			"sourceL3": int,
			"dxyL1": float,
			"dxyL2": float,
			"dxyL3": float,
			"dxyL4": float,
			"dzL1": float,
			"dzL2": float,
			"dzL3": float,
			"dzL4": float,
			"dR12": float,
			"dR13": float,
			"dR23": float,
			"m3l": float,
			"m4l": float,
			"mt": float,
			"met": float,
			"met_phi": float,
			"genWeight": float,
			"pileupWeight": float,
			"passedDiMu0": int,
			"passedDiMu1": int,
			"passedDiMu2": int,
			"passedTriMu": int,
			#"gen_dPtL1": float,
			#"gen_dPtL2": float,
			#"gen_dPtL3": float,
			#"gen_dRL1": float,
			#"gen_dRL2": float,
			#"gen_dRL3": float,
			"photon_mass": float,
			"inAcceptance": int,
			"GenWMass": float,
			#"softMvaIdL3": int,
			#"highPtIdL3": int,
			}


for branch in branches:
	#output[branch] = np.array([])
	output[branch] = []

